[package]
name = "jm-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.60", features = ["Win32_Networking_WinInet"]}
serde_json = "1.0.132"
image = "0.25.4"
base64 = "0.21"
md5 = "0.7"
